<!DOCTYPE html>
<html lang="rus">
<head>
	<meta charset="UTF-8">
	<title>Типы подключения</title>
	<link rel="stylesheet" type="text/css" href="css/page-style.css">
	<link rel="stylesheet" href="css/style.css">	
</head>
<body>

<div class="page">

<?php
require('header.php');
?>
	<main class="content">
		<article class="post  single-post">
				<div class="post__entry">
					<div id="toc_container" class="no_bullets"><p class="toc_title">Содержание</p><ul class="toc_list"><li><a href="#i">Предназначение</a></li><li><a href="#SCSI_8212Small_Computer_System_Interface">SCSI —&nbsp;Small Computer System Interface</a></li><li><a href="#SAS_8212Serial_Attached_SCSI">SAS —&nbsp;Serial Attached SCSI</a></li><li><a href="#Firewire_8212IEEE_1394">Firewire —&nbsp;IEEE 1394</a></li><li><a href="#IDE_8212Integrated_Drive_Electronics">IDE —&nbsp;Integrated Drive Electronics</a></li><li><a href="#SATA_8212Serial_ATA">SATA —&nbsp;Serial ATA</a></li><li><a href="#eSATA_8212External_SATA">eSATA —&nbsp;External SATA</a></li><li><a href="#i-2">Заключение</a></li></ul></div>
					<h2><span id="i">Предназначение</span></h2>
					<p>Интерфейсы жестких дисков (или строго говоря, интерфейсы внешних накопителей, поскольку в их качестве могут выступать не только жесткие диски, но и другие типы накопителей, например, приводы для оптических дисков) предназначены для обмена информацией между этими устройствами внешней памяти и материнской платой. Интерфейсы жестких дисков, не в меньшей степени, чем физические параметры накопителей, влияют на многие рабочие характеристики накопителей и на их производительность. В частности, интерфейсы накопителей определяют такие их параметры, как&nbsp; скорость обмена данными между жестким диском и материнской платой, количество устройств, которые можно подключить к компьютеру, возможность создания дисковых массивов, возможность горячего подключения, поддержка технологий NCQ и AHCI, и.т.д. Также от интерфейса жесткого диска зависит, какой кабель, шнур или переходник для его подключения к материнской плате вам потребуется.</p>
					<h2><span id="SCSI_8212Small_Computer_System_Interface">SCSI —&nbsp;Small Computer System Interface</span></h2>
					<p>Интерфейс SCSI является одним из самых старых интерфейсов, разработанных для подключения накопителей в персональных компьютерах. Появился данный стандарт еще в начале 1980-х гг. Одним из его разработчиков был Алан Шугарт, также известный, как изобретатель дисководов для гибких дисков.</p>
					<div id="attachment_2233" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2233 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SCSI_2_630x420.jpg" alt="Интерфейс SCSI" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SCSI_2_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SCSI_2_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Внешний вид интерфейса SCSI на плате и кабеля подключения к нему</div></div>
					<p>Стандарт SCSI (традиционно данная аббревиатура читается в русской транскрипции как «скази») первоначально предназначался для использования в персональных компьютерах, о чем свидетельствует даже само название формата – Small Computer System Interface, или системный интерфейс для небольших компьютеров. Однако так получилось, что накопители данного типа применялись в основном в персональных компьютерах топ-класса, а впоследствии и в серверах. Связано это было с тем, что, несмотря на удачную архитектуру и широкий набор команд, техническая реализация интерфейса была довольно сложна, и не подходила по стоимости для массовых ПК.</p>
					<p>Тем не менее, данный стандарт обладал рядом возможностей, недоступных для прочих типов интерфейсов. Например, шнур для подключения устройств Small Computer System Interface может иметь максимальную длину в 12 м,&nbsp; а скорость передачи данных – 640 МБ/c.</p>
					<p>Как и появившийся несколько позже интерфейс IDE, интерфейс SCSI является параллельным. Это означает, что в интерфейсе применяются шины, передающие информацию по нескольким проводникам. Данная особенность являлась одним из сдерживающих факторов для развития стандарта, и поэтому в качестве его замены был разработан более совершенный, последовательный стандарт SAS (от Serial Attached SCSI).</p>
					<h2><span id="SAS_8212Serial_Attached_SCSI">SAS —&nbsp;Serial Attached SCSI</span></h2>
					<div id="attachment_2234" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2234 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SAS_3_630x420.jpg" alt="Пример интерфейса SAS" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SAS_3_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SAS_3_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Так выглядит интерфейс SAS серверного диска</div></div>
					<p>Serial Attached SCSI разрабатывался в усовершенствования достаточно старого интерфейса подключения жестких дисков Small Computers System Interface. Несмотря на то, что Serial Attached SCSI&nbsp; использует&nbsp; основные достоинства своего предшественника, тем не менее, у него есть немало преимуществ. Среди них стоит отметить следующие:</p>
					<ul>
					<li>Использование общей шины всеми устройствами.</li>
					<li>Последовательный протокол передачи данных, используемый &nbsp;SAS, позволяет задействовать меньшее количество сигнальных линий.</li>
					<li>Отсутствует необходимость в терминации шины.</li>
					<li>Практически неограниченное число подключаемых устройств.</li>
					<li>Более высокая пропускная способность (до 12 Гбит/c). В будущих реализациях протокола SAS предполагается поддерживать скорость обмена данными до 24 Гбит/c.</li>
					<li>Возможность подключения к контроллеру SAS накопителей с интерфейсом Serial ATA.</li>
					</ul>
					<p>Как правило, системы Serial Attached SCSI строятся на основе нескольких компонентов. В число основных компонентов входят:</p>
					<ul>
					<li>Целевые устройства. В эту категорию включают собственно накопители или дисковые массивы.</li>
					<li>Инициаторы – микросхемы, предназначенные для генерации запросов к целевым устройствам.</li>
					<li>Система доставки данных – кабели, соединяющие целевые устройства и инициаторы</li>
					</ul>
					<p>Разъемы Serial Attached SCSI могут иметь различную форму и размер, в зависимости от типа (внешний или внутренний) и от версий SAS. Ниже представлены внутренний разъем SFF-8482 и внешний разъем SFF-8644, разработанный для SAS-3:</p>
					<div id="attachment_2235" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2235 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SFF-8482_4_630x420.jpg" alt="Типы разъёмов SAS" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SFF-8482_4_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SFF-8482_4_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Слева — внутренний разъём SAS SFF-8482; Справа — внешний разъём SAS SFF-8644 с кабелем.</div></div>
					<p>Несколько примеров внешнего вида шнуров и переходников SAS: шнур HD-Mini SAS и шнур-переходник SAS-Serial ATA.</p>
					<div id="attachment_2236" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2236 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SAS-SerialATA_5_630x420.jpg" alt="Шнуры SAS" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SAS-SerialATA_5_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SAS-SerialATA_5_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Слева — шнур HD Mini SAS; Справа — переходной шнур с SAS на Serial ATA</div></div>
					<h2><span id="Firewire_8212IEEE_1394">Firewire —&nbsp;IEEE 1394</span></h2>
					<p>Сегодня достаточно часто можно встретить жесткие диски с интерфейсом Firewire. Хотя через интерфейс Firewire к компьютеру можно подключить любые типы периферийных устройств, и его нельзя назвать специализированным интерфейсом, предназначенным&nbsp; для подключения исключительно жестких дисков, тем не менее, Firewire имеет ряд особенностей, которые делают его чрезвычайно удобным для этой цели.</p>
					<div id="attachment_2238" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2238 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-firewire_6_630x420.jpg" alt="Вид интерфейса FireWire" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-firewire_6_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-firewire_6_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">FireWire — IEEE 1394 — вид на ноутбуке</div></div>
					<p>Интерфейс Firewire был разработан в середине 1990-х гг. Начало разработке положила небезызвестная фирма Apple, нуждавшаяся в собственной, отличной от USB, шине для подключения периферийного оборудования, прежде всего мультимедийного. Спецификация, описывающая работу шины Firewire, получила название IEEE 1394.</p>
					<p>На сегодняшний день Firewire представляет собой один из наиболее часто используемых форматов высокоскоростной последовательной внешней шины. К основным особенностям стандарта можно отнести:</p>
					<ul>
					<li>Возможность горячего подключения устройств.</li>
					<li>Открытая архитектура шины.</li>
					<li>Гибкая топология подключения устройств.</li>
					<li>Меняющаяся в широких пределах скорость передачи данных – от 100 до 3200 Мбит/c.</li>
					<li>Возможность передачи данных между устройствами без участия компьютера.</li>
					<li>Возможность организации локальных сетей при помощи шины.</li>
					<li>Передача питания по шине.</li>
					<li>Большое количество подключаемых устройств (до 63).</li>
					</ul>
					<p>Для подключения винчестеров (обычно посредством внешних корпусов для жестких дисков) через шину Firewire, как правило, используется специальный стандарт SBP-2, использующий набор команд протокола Small Computers System Interface. Существует возможность подключения устройств Firewire к обычному разъему USB, но для этого требуется специальный переходник.</p>
					<h2><span id="IDE_8212Integrated_Drive_Electronics">IDE —&nbsp;Integrated Drive Electronics</span></h2>
					<p>Аббревиатура IDE, несомненно, известна большинству пользователей персональных компьютеров. Стандарт интерфейса для подключения жестких дисков IDE был разработан известной фирмой, производящей жесткие диски – Western Digital. Преимуществом IDE по сравнению&nbsp; с другими существовавшими в то время интерфейсами, в частности,&nbsp; интерфейсом Small Computers System Interface, а также стандартом ST-506, было отсутствие необходимости устанавливать контроллер жесткого диска на материнскую плату. Стандарт IDE подразумевал установку контроллера привода на корпус самого накопителя, а на материнской плате оставался лишь хост-адаптер интерфейса для подключения приводов IDE.</p>
					<div id="yandex_rtb_flat9172_R-A-152619-10"></div>
					<div id="attachment_2239" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2239 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE_7_630x420.jpg" alt="Вид интерфейса IDE" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE_7_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE_7_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Интерфейс IDE на материнской плате</div></div>
					<p>Данное нововведение позволило улучшить параметры работы накопителя IDE благодаря тому, что сократилось расстояние между контроллером и самим накопителем. Кроме того, установка контроллера IDE внутрь корпуса жесткого диска позволила несколько упростить как материнские платы, так и производство самих винчестеров, поскольку технология давала свободу производителям в плане оптимальной организации логики работы накопителя.</p>
					<p>Новая технология первоначально получила название Integrated Drive Electronics (Встроенная в накопитель электроника). Впоследствии был разработан описывающий ее стандарт, названный ATA. Это название происходит от последней части названия семейства компьютеров&nbsp; PC/AT посредством добавления слова Attachment.</p>
					<p>Для подключения жесткого диска или другого устройства, например, накопителя для оптических дисков, поддерживающего технологию Integrated Drive Electronics, к материнской плате, используется специальный кабель IDE. Поскольку ATA относится к параллельным интерфейсам (поэтому его также называют Parallel ATA или PATA), то есть, интерфейсам, предусматривающим одновременную передачу данных&nbsp; по нескольким линиям, то его кабель данных имеет большое количество проводников (обычно 40, а в последних версиях протокола имелась возможность использовать 80-жильный кабель).&nbsp; Обычный кабель данных для данного стандарта имеет плоский и широкий вид, но встречаются и кабели круглого сечения. Кабель питания для накопителей Parallel ATA имеет 4-контактный разъем и подсоединен к блоку питания компьютера.</p>
					<p>Ниже приведены примеры кабеля IDE и круглого шнура данных PATA:</p>
					<div id="attachment_2240" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2240 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE-and-PATA_8_630x420.jpg" alt="Интерфейсы IDE и PATA" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE-and-PATA_8_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE-and-PATA_8_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Внешний вид интерфейсного кабеля: cлева — плоский, справа в круглой оплетке — PATA или IDE.</div></div>
					<p>Благодаря сравнительной дешевизне накопителей Parallel ATA, простоте реализации интерфейса на материнской плате, а также простоте установки и конфигурации устройств PATA для пользователя, накопители типа Integrated Drive Electronics на длительное время вытеснили с рынка винчестеров для персональных компьютеров бюджетного уровня устройства других типов интерфейса.</p>
					<p>Однако стандарт PATA имеет и ряд недостатков. Прежде всего, это ограничение по длине, которую может иметь кабель данных Parallel ATA – не более 0,5 м. Кроме того, параллельная организация интерфейса накладывает ряд ограничений на максимальную скорость передачи данных. Не поддерживает стандарт PATA и многие расширенные возможности, которые имеются у других типов интерфейсов, например, горячее подключение устройств.</p>
					<h2><span id="SATA_8212Serial_ATA">SATA —&nbsp;Serial ATA</span></h2>
					<div id="attachment_2241" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2241 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA_9_630x420.jpg" alt="Интерфейс SATA" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA_9_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA_9_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Вид интерфейса SATA на материнской плате</div></div>
					<p>Интерфейс SATA (Serial ATA), как можно догадаться из названия, является усовершенствованием ATA. Заключается это усовершенствование, прежде всего, в переделке традиционного параллельного ATA (Parallel ATA) в последовательный интерфейс. Однако этим отличия стандарта Serial ATA от традиционного не ограничиваются. Помимо изменения типа передачи данных с параллельного на последовательный, изменились также разъемы для передачи данных и электропитания.</p>
					<p>Ниже приведен шнур данных SATA:</p>
					<div id="attachment_2242" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2242 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA-cable_10_630x420.jpg" alt="SATA кабель" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA-cable_10_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA-cable_10_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Шнур передачи данных для SATA интерфейса</div></div>
					<p>Это позволило использовать шнур значительно большей длины и увеличить скорость передачи данных. Однако минусом стало то обстоятельство, что устройства PATA, которые до появления SATA присутствовали на рынке в огромных количествах, стало невозможно напрямую подключить в новые разъемы. Правда, большинство новых материнских плат все же имеют старые разъемы и поддерживают подключение старых устройств. Однако обратная операция – подключение накопителя нового типа к старой материнской плате обычно вызывает куда больше проблем. Для этой операции пользователю обычно требуется переходник Serial ATA to PATA. Переходник для кабеля питания обычно имеет сравнительно простую конструкцию.</p>
					<p>Переходник питания&nbsp;Serial ATA to PATA:</p>
					<div id="attachment_2243" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2243 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-PATA-SATA-_11_630x420.jpg" alt="Переходник PATA-Serial ATA" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-PATA-SATA-_11_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-PATA-SATA-_11_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Слева общий вид кабеля; Cправа укрупнено внешний вид коннекторов PATA и Serial ATA</div></div>
					<p>Сложнее, однако, дело обстоит с таким устройством, как переходник для подключения устройства последовательного интерфейса в разъем для параллельного интерфейса. Обычно переходник такого типа выполнен в виде небольшой микросхемы.</p>
					<div id="attachment_2244" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2244 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-Bi-Directional-SATA-IDE_12_630x420.jpg" alt="Переходник Bi-Directional SATA-IDE " width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-Bi-Directional-SATA-IDE_12_630x420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-Bi-Directional-SATA-IDE_12_630x420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Внешний вид универсального двунаправленного переходника между интерфейсами SATA — IDE</div></div>
					<p>В настоящее время интерфейс Serial ATA практически вытеснил Parallel ATA, и накопители PATA можно встретить теперь в основном лишь в достаточно старых компьютерах. Еще одной особенностью нового стандарта, обеспечившей его широкую популярность, стала поддержка технологий NCQ и AHCI.</p>
					<div id="attachment_2245" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2245 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE-to-SATA_13_630х420.jpg" alt="Переходник IDE - SATA" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE-to-SATA_13_630х420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-IDE-to-SATA_13_630х420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Вид переходника с IDE на SATA</div></div>
					<p>О технологии NCQ можно рассказать чуть подробнее. Основное&nbsp; преимущество NCQ состоит в том, что она позволяет использовать идеи, которые давно были реализованы в протоколе SCSI. В частности, NCQ поддерживает систему упорядочивания операций чтения/записи, поступающих к нескольким накопителям, установленным в системе.&nbsp; Таким образом, NCQ способна значительно повысить производительность работы накопителей, в особенности массивов жестких дисков.</p>
					<div id="attachment_2246" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2246 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA-to-IDE_14_630х420.jpg" alt="Переходник SATA - IDE" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA-to-IDE_14_630х420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-SATA-to-IDE_14_630х420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Вид переходника с SATA на IDE</div></div>
					<p>Для использования NCQ необходима поддержка технологии со стороны жесткого диска, а также хост-адаптера материнской платы. Практически&nbsp; все адаптеры, поддерживающие AHCI, поддерживают и NCQ. Кроме того, NCQ поддерживают и некоторые старые проприетарные адаптеры. Также для работы NCQ требуется ее поддержка со стороны операционной системы.</p>
					<h2><span id="eSATA_8212External_SATA">eSATA —&nbsp;External SATA</span></h2>
					<p>Отдельно стоит упомянуть о казавшемся многообещающим в свое время, но так и не получившем широкого распространения формате eSATA (External SATA). Как можно догадаться из названия, eSATA представляет собой разновидность Serial ATA, предназначенную для подключения исключительно внешних накопителей. Стандарт eSATA предлагает для внешних устройств большую часть возможностей стандартного, т.е. внутреннего Serial ATA, в частности, одинаковую систему сигналов и команд и столь же высокую скорость.</p>
					<div id="attachment_2248" class="wp-caption aligncenter" style="max-width: 630px;"><img class="wp-image-2248 size-full" src="//biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-eSATA_14_630х420.jpg" alt="Интерфейс eSATA" width="630" height="420" srcset="https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-eSATA_14_630х420.jpg 630w, https://biosgid.ru/wp-content/uploads/2015/07/HDD-inerfaces-eSATA_14_630х420-300x200.jpg 300w" sizes="(max-width: 630px) 100vw, 630px"><div class="wp-caption-text">Разъем eSATA на ноутбуке</div></div>
					<p>Тем не менее, у eSATA есть и некоторые отличия от породившего его стандарта внутренней шины. В частности, eSATA поддерживает более длинный кабель данных (до 2 м), а также имеет более высокие требования к питанию накопителей. Кроме того, разъемы eSATA несколько отличаются от стандартных разъемов Serial ATA.</p>
					<p>По сравнению с другими внешними шинами, такими, как USB и Firewire, eSATA, однако, имеет один существенный недостаток. Если эти шины позволяют осуществлять электропитание устройства через сам кабель шины, то накопитель eSATA требует специальные разъемы для питания. Поэтому, несмотря на сравнительно высокую скорость передачи данных, eSATA в настоящее время не пользуется большой популярностью в качестве интерфейса для подключения внешних накопителей.</p>
					<h2><span id="i-2">Заключение</span></h2>
					<p>Информация, хранящаяся на жестком диске, не может стать полезной для пользователя и доступной для прикладных программ до тех пор, пока к ней не получит доступ центральный процессор компьютера. Интерфейсы жестких дисков представляют собой средство для связи между этими накопителями и материнской платой. На сегодняшний день существует немало различных типов интерфейсов жестких дисков, каждый из которых имеет свои достоинства, недостатки и характерные особенности. Надеемся, что приведенная в данной статье информация во многом окажется&nbsp; полезной для читателя, ведь выбор современного жесткого диска во многом определяются не только его внутренними&nbsp; характеристиками, такими, как емкость, объем кэш-памяти, скорость доступа и вращения, но и тем интерфейсом, для которого он был разработан.</p>
					<div id="yandex_rtb_flat2549_R-A-152619-12"></div>
					<div class="flat_pm_end"></div>
				</div><!-- .post__entry -->
			</article><!-- .post -->
		</main><!-- .content -->
</div><!-- .page -->
<div id="wt-sky-root"></div></body>
</html>